[tool.poetry]
name = "ziya"
version = "0.2.3"
description = ""
authors = ["Vishnu Krishnaprasad <vishnukool@gmail.com>"]
readme = "README.md"

packages = [
    { include = "app", from ="." },
]

include = [
    "templates/**/*",  # Include all files in templates directory
    "app/templates/**/*",  # Include all files in templates directory
    "app/utils/ast_parser/ts_parser/**/*",  # Include all files in ts_parser
    "LICENSE",
    "README.md",
    "MANIFEST.in",
    "scripts/**/*",    # Include all files in scripts directory
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
uvicorn = "^0.23.2"
whatthepatch = ">=1.0.2"
patch-ng = ">=1.17"
pydantic = "^2.9.2"
jinja2 = "^3.1.3"
tiktoken = "^0.8.0"
boto3 = "^1.34.88"
langchain-aws = ">=0.2,<0.3"
langchain-google-genai = "^2.1.0"
langchain = ">=0.3,<0.4"
langgraph = ">=0.2,<0.3"
langchainhub = ">=0.1.15"
langchain-anthropic = ">=0.2,<0.3"
langchain-cli = ">=0.0.15"
pydevd-pycharm = "^243.18137.19"
langchain-community = "^0.3.1"
transformers = "^4.36.2"
setuptools = ">=68.0.0"
# AST parsing dependencies
cssutils = ">=2.6.0"
html5lib = ">=1.1"
tqdm = "^4.66.1"
# Document extraction dependencies
PyPDF2 = "^3.0.1"
pdfplumber = "^0.10.0"
python-docx = "^1.1.0"
openpyxl = "^3.1.2"
pandas = "^2.1.0"
python-pptx = "^0.6.21"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.poetry.scripts]
ziya = 'app.ziya_exec:ziya'
dev = 'app.ziya_exec:dev'
finstall = "app.ziya_exec:frontend_install"
fstart = "app.ziya_exec:frontend_start"
fbuild = "app.ziya_exec:frontend_build"

[tool.poetry.build]
script = "build_script.py"
generate-setup-file = true

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=42", "wheel"]
build-backend = "poetry.core.masonry.api"
