[tool.poetry]
name = "ziya"
version = "0.2.0"
description = ""
authors = ["Vishnu Krishnaprasad <vishnukool@gmail.com>"]
readme = "README.md"
include = ["templates/**/*", "pyproject.toml" ,"ziya_exec.py", "app/utils/ast_parser/ts_parser"]
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
uvicorn = "^0.23.2"
whatthepatch = ">=1.0.2"
patch-ng = ">=1.17"
pydantic = "^2.9.2"
jinja2 = "^3.1.3"
tiktoken = "^0.8.0"
boto3 = "^1.34.88"
langchain-aws = ">=0.2,<0.3"
langchain = ">=0.3,<0.4"
langgraph = ">=0.2,<0.3"
langchainhub = ">=0.1.15"
langchain-anthropic = ">=0.2,<0.3"
langchain-cli = ">=0.0.15"
pydevd-pycharm = "^243.18137.19"
langchain-community = "^0.3.1"
transformers = "^4.36.2"
# AST parsing dependencies
cssutils = ">=2.6.0"
html5lib = ">=1.1"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ziya = 'ziya_exec:ziya'
dev = 'ziya_exec:dev'
finstall = "ziya_exec:frontend_install"
fstart = "ziya_exec:frontend_start"
fbuild = "ziya_exec:frontend_build"

[build-system.hooks.typescript-install]
install-script = "scripts/install_typescript.py"
